[workspace]
resolver = "2"
members = ["pw-splitter"]

[profile.profile]
inherits = "release"
strip = false
debug = true

[profile.bench]
inherits = "profile"

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = "abort"
debug = "full"
split-debuginfo = "packed"
